# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  title: "Chenghan Xie | Stanford Operations Research Ph.D. Student"
  params:
    description: "Official personal website of Chenghan Xie, a Ph.D. student in Operations Research at Stanford University working on generative models, diffusion models, and AI impact in financial markets."
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
